### ISSUE TITLE
cannot find detected_ objects_ Visualizer

### ISSUE THREAD

**Issue by han7937** [HMX2013/RANSAC-L-shape-fitting-3D-LiDAR-ROS#1]
Thank you for your open source. Running the launch produces the following results

`setting /run_id to 71d585c6-4560-11ed-836e-60e32bea2b35
process[rosout-1]: started with pid [22599]
started core service [/rosout]
process[ransac_lshape_fitting-2]: started with pid [22603]
ERROR: cannot launch node of type [detected_objects_visualizer/visualize_detected_objects]: detected_objects_visualizer
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/hz/lsharp_ws/src
ROS path [2]=/home/hz/point_ws/src
ROS path [3]=/opt/ros/melodic/share
process[rviz-4]: started with pid [22607]
[ INFO] [1665051605.139284228]: Input_cluster_topic: /segmentation/detected_objects
[ INFO] [1665051605.140007673]: output_bbox_topic_: /l_shape_fitting/bbox_visual_jsk
`
, cannot find detected_ objects_ Visualizer, you need to install autoware_ ai_ visualization
？

**Comment by HMX2013** [comment]
It's the visualization node from autoware.ai, you can comment out or delete the following part.
  <node pkg="detected_objects_visualizer" type="visualize_detected_objects" name="shape_estimation_visualization"
        output="screen" ns="/$(arg namespace)/$(arg packagename)"/>

**Comment by morte2025** [comment]
It's the visualization node you can find in autoware.ai, you can comment out or delete the following part in the launch file.
  <node pkg="detected_objects_visualizer" type="visualize_detected_objects" name="shape_estimation_visualization"
        output="screen" ns="/$(arg namespace)/$(arg packagename)"/>

**Comment by han7937** [comment]
Thank you for your answer, I will close the question
