### ISSUE TITLE
 Where is obsdet_msgs in the code?

### ISSUE THREAD

**Issue by Healthy-zhu** [HMX2013/RANSAC-L-shape-fitting-3D-LiDAR-ROS#3]

**Comment by morte2025** [comment]
https://drive.google.com/file/d/1ztLk9Slm656CV-WJieUpBJPlz-Iw14Bk/view?usp=share_link

**Comment by Healthy-zhu** [comment]
I'm very sorry to bother you again! But the message type you provided does not match the code.
/home/common/ransac_l_fitting_shape/src/RANSAC-L-shape-fitting-3D-LiDAR-ROS-main/src/ransac_Lshape_fitting.cpp: In member function ‘void LShapeFilter::MainLoop(const CloudClusterArray&)’:
/home/common/ransac_l_fitting_shape/src/RANSAC-L-shape-fitting-3D-LiDAR-ROS-main/src/ransac_Lshape_fitting.cpp:600:37: error: ‘const struct obsdet_msgs::CloudCluster_<std::allocator<void> >’ has no member named ‘orientation’
     double theta_kitti = in_cluster.orientation;
                                     ^~~~~~~~~~~
/home/common/ransac_l_fitting_shape/src/RANSAC-L-shape-fitting-3D-LiDAR-ROS-main/src/ransac_Lshape_fitting.cpp:602:58: error: ‘const struct obsdet_msgs::CloudCluster_<std::allocator<void> >’ has no member named ‘index’
     eval_performance(theta_kitti, theta_star, in_cluster.index, in_cluster.index_seq);
                                                          ^~~~~
/home/common/ransac_l_fitting_shape/src/RANSAC-L-shape-fitting-3D-LiDAR-ROS-main/src/ransac_Lshape_fitting.cpp:602:76: error: ‘const struct obsdet_msgs::CloudCluster_<std::allocator<void> >’ has no member named ‘index_seq’
 l_performance(theta_kitti, theta_star, in_cluster.index, in_cluster.index_seq);

**Comment by morte2025** [comment]
https://drive.google.com/file/d/1ztLk9Slm656CV-WJieUpBJPlz-Iw14Bk/view?usp=share_link    

you can also check out my method https://github.com/HMX2013/Covex-hull-based-fitting-3D-LiDAR-ROS, the ransac method has poor performance.
